export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_TRENDING = 'GET_TRENDING';
export const GET_NOW_PLAYING_MOVIE = 'GET_NOW_PLAYING_MOVIE';
export const GET_POPULAR_MOVIE = 'GET_POPULAR_MOVIE';
export const GET_TOP_RATED_MOVIE = 'GET_TOP_RATED_MOVIE';
